### ISSUE TITLE
Next-auth Google SignIn Provider: Invalid `p.account.create()` invocation ->  The provided value for the column is too long for the column's type

### ISSUE THREAD

**Issue by exponent42** [planetscale/nextjs-planetscale-starter#3]
Hello, 

Google signin provider added to `[...nextauth].ts` as per next-auth's docs returns `[next-auth][error][adapter_error_linkAccount]` on `p.account.create()`.

Ref [this issue](https://github.com/prisma/prisma/discussions/4079#discussioncomment-120970):

> The base issue seems to be that the String scalar in prisma.schema maps to varchar(191) in MySQL (instead of "text"), despite being mapped to "text" in PostgreSQL and SqlLite.

Amending `Account` columns to incl `@db.Text` or `@db.VarChar(500)` made no diff, same error. 

Reproduce (+Google signIn provider): https://github.com/exponent42/nextjs-planetscale-starter

Frontend dev by nature so apologise if this is obvious.

Really enjoying the combination of PS and prisma btw, ty for creating this repo :)

**Comment by tbarn** [comment]
Hey @exponent42! Good question. I tested it with a few providers but hadn't seen this error before. Does the error message say what column it is?

**Comment by exponent42** [comment]
Hi @tbarn that would help sorry. Not sure to be honest, does this make more sense to you?

```bash
[next-auth][error][adapter_error_linkAccount] 
https://next-auth.js.org/errors#adapter_error_linkaccount 
Invalid `p.account.create()` invocation in
/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: (data) => p.user.update({ where: { id: data.id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create(
  The provided value for the column is too long for the column's type. Column: 22001) {
  message: '\n' +
    '\x1B[31mInvalid \x1B[1m`p.account.create()`\x1B[22m invocation in\x1B[39m\n' +
    '\x1B[31m\x1B[4m/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\x1B[24m\x1B[39m\n' +
    '\n' +
    '\x1B[2m  \x1B[90m16 \x1B[39m\x1B[38;5;109m}\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[2m  \x1B[90m17 \x1B[39mupdateUser\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mdata\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39muser\x1B[38;5;109m.\x1B[39m\x1B[36mupdate\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[38;5;109m{\x1B[39m where\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m{\x1B[39m id\x1B[38;5;109m:\x1B[39m data\x1B[38;5;109m.\x1B[39mid \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m,\x1B[39m data \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m)\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[2m  \x1B[90m18 \x1B[39mdeleteUser\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mid\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39muser\x1B[38;5;109m.\x1B[39m\x1B[36mdelete\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[38;5;109m{\x1B[39m where\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m{\x1B[39m id \x1B[38;5;109m}\x1B[39m \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m)\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[31m\x1B[1m→\x1B[22m\x1B[39m \x1B[2m\x1B[90m19 \x1B[39mlinkAccount\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mdata\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39maccount\x1B[38;5;109m.\x1B[39m\x1B[36mcreate\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[22m\n' +
    "  The provided value for the column is too long for the column's type. Column: 22001)",
  stack: 'Error: \n' +
    '\x1B[31mInvalid \x1B[1m`p.account.create()`\x1B[22m invocation in\x1B[39m\n' +
    '\x1B[31m\x1B[4m/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42\x1B[24m\x1B[39m\n' +
    '\n' +
    '\x1B[2m  \x1B[90m16 \x1B[39m\x1B[38;5;109m}\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[2m  \x1B[90m17 \x1B[39mupdateUser\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mdata\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39muser\x1B[38;5;109m.\x1B[39m\x1B[36mupdate\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[38;5;109m{\x1B[39m where\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m{\x1B[39m id\x1B[38;5;109m:\x1B[39m data\x1B[38;5;109m.\x1B[39mid \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m,\x1B[39m data \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m)\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[2m  \x1B[90m18 \x1B[39mdeleteUser\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mid\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39muser\x1B[38;5;109m.\x1B[39m\x1B[36mdelete\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[38;5;109m{\x1B[39m where\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m{\x1B[39m id \x1B[38;5;109m}\x1B[39m \x1B[38;5;109m}\x1B[39m\x1B[38;5;109m)\x1B[39m\x1B[38;5;109m,\x1B[39m\x1B[22m\n' +
    '\x1B[31m\x1B[1m→\x1B[22m\x1B[39m \x1B[2m\x1B[90m19 \x1B[39mlinkAccount\x1B[38;5;109m:\x1B[39m \x1B[38;5;109m(\x1B[39mdata\x1B[38;5;109m)\x1B[39m => p\x1B[38;5;109m.\x1B[39maccount\x1B[38;5;109m.\x1B[39m\x1B[36mcreate\x1B[39m\x1B[38;5;109m(\x1B[39m\x1B[22m\n' +
    "  The provided value for the column is too long for the column's type. Column: 22001)\n" +
    '    at cb (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@prisma/client/runtime/index.js:38537:17)\n' +
    '    at async acc.<computed> (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/errors.js:92:16)\n' +
    '    at async callbackHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/lib/callback-handler.js:180:7)\n' +
    '    at async Object.callback (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/routes/callback.js:117:13)\n' +
    '    at async NextAuthHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/index.js:103:28)\n' +
    '    at async NextAuthNextHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/next/index.js:40:7)\n' +
    '    at async /Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/next/index.js:80:32\n' +
    '    at async Object.apiResolver (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/api-utils.js:102:9)\n' +
    '    at async DevServer.handleApiRequest (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/next-server.js:1014:9)\n' +
    '    at async Object.fn (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/next-server.js:901:37)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `p.account.create()` invocation in
/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: (data) => p.user.update({ where: { id: data.id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create(
  The provided value for the column is too long for the column's type. Column: 22001) Error: 
Invalid `p.account.create()` invocation in
/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@next-auth/prisma-adapter/dist/index.js:19:42

  16 },
  17 updateUser: (data) => p.user.update({ where: { id: data.id }, data }),
  18 deleteUser: (id) => p.user.delete({ where: { id } }),
→ 19 linkAccount: (data) => p.account.create(
  The provided value for the column is too long for the column's type. Column: 22001)
    at cb (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/@prisma/client/runtime/index.js:38537:17)
    at async acc.<computed> (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/errors.js:92:16)
    at async callbackHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/lib/callback-handler.js:180:7)
    at async Object.callback (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/routes/callback.js:117:13)
    at async NextAuthHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/core/index.js:103:28)
    at async NextAuthNextHandler (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/next/index.js:40:7)
    at async /Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next-auth/next/index.js:80:32
    at async Object.apiResolver (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/api-utils.js:102:9)
    at async DevServer.handleApiRequest (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/Users/uwotm9/dev/playground/replicate-pscale-nextjs/node_modules/next/dist/server/next-server.js:901:37) {
  name: 'LinkAccountError'
}

```

**Comment by exponent42** [comment]
Hi @tbarn the culprit column is `id_token`

It's a bit cryptic as `22001` - any idea why it's not explicitly naming the column/s on errors like this?

**Comment by tbarn** [comment]
I think it has something to do with how MySQL errors filter up through Prisma. I see your #4 PR. I will run through it soon, although I think it looks like a good change. Thanks for submitting that!
